repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml", "-r", "src", "tests"]
        additional_dependencies: ["bandit[toml]"]

# Temporarily disabled while we add type annotations
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.9.0
#   hooks:
#     - id: mypy
#       additional_dependencies:
#         - types-requests
#         - pydantic
