repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/python-poetry/poetry
    rev: '2.0.0'  # Must be updated manually (see https://python-poetry.org/docs/pre-commit-hooks/#why-does-pre-commit-autoupdate-not-update-to-the-latest-version
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.2
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml", "-r", "src", "tests"]
        additional_dependencies: ["bandit[toml]"]

# Temporarily disabled while we add type annotations
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.9.0
#   hooks:
#     - id: mypy
#       additional_dependencies:
#         - types-requests
#         - pydantic
