services:
  api:
    build: .
    container_name: contention-classification-api
    ports:
      - "8120:8120"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8120/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: no
    environment:
      - ENVIRONMENT=local
    volumes:
      - .:/app
    security_opt:
      - no-new-privileges:true
