[tool.pytest.ini_options]
addopts = "-ra --cov=./src --cov-fail-under=80 --no-cov-on-fail --cov-report=term:skip-covered --cov-report=html:build/reports/coverage --cov-branch"
testpaths = [
    "tests"
]

[tool.coverage.run]
omit = [
    "src/python_src/pull_api_documentation.py",
]

[tool.ruff]
line-length = 127
target-version = "py312"
exclude = [".git", "__pycache__", "build", "dist"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
]
ignore = []

[tool.ruff.format]
quote-style = "double"
line-ending = "lf"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.mypy]
python_version = "3.12"
plugins = ['pydantic.mypy']
strict = true
ignore_missing_imports = true
exclude = [
    "scripts"
]

[tool.poetry]
name = "contention-classification-api"
version = "0.1.0"
description = "API for classifying contentions from 526 submissions"
authors = ["Department of Veterans Affairs"]
readme = "README.md"
license = "LICENSE.md"
homepage = "https://github.com/department-of-veterans-affairs/contention-classification-api"
repository = "https://github.com/department-of-veterans-affairs/contention-classification-api"
keywords = ["veterans", "contention", "classification", "api", "fastapi"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
]
packages = [{include = "python_src", from = "src"}]

[tool.poetry.dependencies]
python = "3.12.3"
fastapi = "0.115.6"
httpx = "0.28.1"
pydantic = "2.10.4"
setuptools = "75.7.0"
uvicorn = {extras = ["standard"], version = "0.34.0"}

[tool.poetry.group.dev.dependencies]
mypy = "1.14.1"
pre-commit = "4.0.1"
ruff = "0.8.6"
pytest = "8.3.4"
pytest-cov = "6.0.0"
bandit = {version = "1.8.0", extras = ["toml"]}

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B101"]  # Skip assert warnings in tests

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
