[tool.poetry]
name = "contention-classification-api"
version = "0.1.0"
description = "API for classifying contentions"
authors = ["Department of Veterans Affairs"]
readme = "README.md"
packages = [{include = "python_src", from = "src"}]

[tool.poetry.dependencies]
python = "3.12.3"
fastapi = "^0.115.0"
httpx = "^0.24.0"
pika = "^1.3.0"
pydantic = "^2.6.1"
pytest = "^7.3.1"
setuptools = "^75.6.0"
starlette = "^0.40.0"
uvicorn = {extras = ["standard"], version = "^0.20.0"}

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.1.1"
ruff = "^0.8.5"
mypy = "^1.14.1"
bandit = {extras = ["toml"], version = "^1.8.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100
target-version = "py312"
select = ["E", "F", "B", "I", "N", "UP", "PL", "RUF"]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_optional = true

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B101"]  # Skip assert warnings in tests
