[tool.poetry]
name = "contention-classification-api"
version = "0.1.0"
description = "API for classifying contentions"
authors = ["Department of Veterans Affairs"]
readme = "README.md"
packages = [{include = "python_src", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.0"
httpx = "^0.24.0"
pika = "^1.3.0"
pydantic = "^2.6.1"
pytest = "^7.3.1"
setuptools = "^75.6.0"
starlette = "^0.40.0"
uvicorn = {extras = ["standard"], version = "^0.20.0"}

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
bump-pydantic = "^0.8.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
pre-commit = "^3.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100
