condition_dropdown_table:
  version_number: v0.2
  filename: "CC Taxonomy master"
  input_key:
    - Main condition/term
    - Synonym term 1
    - Synonym term 2
    - Synonym term 3
    - Synonym term 4
    - Legacy term 1
    - Legacy term 2
    - Legacy term 3
    - Legacy term 4
    - Legacy term 5
    - Legacy term 6
    - Legacy term 7
    - Autosuggestion term 1
    - Autosuggestion term 2
    - Autosuggestion term 3
    - Autosuggestion term 4
    - Autosuggestion term 5
    - Autosuggestion term 6
  classification_code: Classification Code
  classification_name: Classification Text
  active_classification: Active classification mapping
diagnostic_code_table:
  version_number: v0.6
  filename: "[Release notes] Diagnostic Code to Classification mapping release notes - DC Lookup"
  input_key: DIAGNOSTIC_CODE
  classification_code: CLASSIFICATION_CODE
  classification_name: CLASSIFICATION_TEXT
autosuggestion_table:
  version_number: v0.2
  filename: "CC Taxonomy master"
  active_autocomplete: Active autosuggestion terms
  autocomplete_terms:
    - Autosuggestion term 1
    - Autosuggestion term 2
    - Autosuggestion term 3
    - Autosuggestion term 4
    - Autosuggestion term 5
    - Autosuggestion term 6
musculoskeletal_lut:
  ankle:
    classification_code: 8991
    classification_name: Musculoskeletal - Ankle
  elbow:
    classification_code: 8993
    classification_name: Musculoskeletal - Elbow
  feet:
    classification_code: 8994
    classification_name: Musculoskeletal - Foot
  foot:
    classification_code: 8994
    classification_name: Musculoskeletal - Foot
  hip:
    classification_code: 8996
    classification_name: Musculoskeletal - Hip
  knee:
    classification_code: 8997
    classification_name: Musculoskeletal - Knee
  low back:
    classification_code: 8998
    classification_name: Musculoskeletal - Mid/Lower Back (Thoracolumbar Spine)
  lower back:
    classification_code: 8998
    classification_name: Musculoskeletal - Mid/Lower Back (Thoracolumbar Spine)
  mid back:
    classification_code: 8998
    classification_name: Musculoskeletal - Mid/Lower Back (Thoracolumbar Spine)
  neck:
    classification_code: 8999
    classification_name: Musculoskeletal - Neck/Upper Back (Cervical Spine)
  shoulder:
    classification_code: 9002
    classification_name: Musculoskeletal - Shoulder
  toe:
    classification_code: 8994
    classification_name: Musculoskeletal - Foot
  toes:
    classification_code: 8994
    classification_name: Musculoskeletal - Foot
  upper back:
    classification_code: 8999
    classification_name: Musculoskeletal - Neck/Upper Back (Cervical Spine)
  wrist:
    classification_code: 9004
    classification_name: Musculoskeletal - Wrist
common_words:
  - left
  - right
  - bilateral
  - in
  - of
  - or
  - the
  - my
  - and
  - chronic
  - to
  - and
  - major
  - than
  - with
  - a
  - va
  - for
  - as
  - has
  - me
  - one
  - use
  - year
  - within
  - worse
  - at
  - have
  - side
  - by
  - frequent
  - mild
  - loud
  - weak
  - bl
  - exam
  - undiagnosed
  - during
  - is
  - when
  - day
  - was
  - all
  - aircraft
  - total
  - moderate
  - noises
  - complete
  - after
  - up
  - it
  - bi
  - daily
  - 'no'
  - had
  - getting
  - also
  - rt
  - sp
  - be
  - see
  - need
  - an
  - which
  - since
  - this
  - jet
  - can't
  - cant
  - pain
  - condition
lut_default_value:
  classification_code: null
  classification_name: null

# AWS Configuration
# Centralized AWS settings used across the application
aws:
  # Environment-specific S3 buckets for the contention classification API
  s3:
    buckets:
      dev: "dsva-vagov-dev-contention-classification-api"
      staging: "dsva-vagov-staging-contention-classification-api"
      sandbox: "dsva-vagov-sandbox-contention-classification-api"
      prod: "dsva-vagov-prod-contention-classification-api"

# Machine Learning Classifier Configuration
# This section configures the ML model used for contention classification
ml_classifier:
  # File naming configuration
  files:
    # Base filenames without paths - paths are constructed dynamically
    model_filename: "LR_tfidf_fit_model_20250623_151434.onnx"
    vectorizer_filename: "LR_tfidf_fit_False_features_20250521_20250623_151434_vectorizer.pkl"

  # Local storage configuration
  storage:
    # Relative path from util directory to model storage location
    local_directory: "models/"

  # S3 object keys (paths within buckets) - uses AWS config from top-level 'aws' section
  s3_objects:
    model: "LR_tfidf_fit_model_20250623_151434.onnx"
    vectorizer: "LR_tfidf_fit_False_features_20250521_20250623_151434_vectorizer.pkl"

  # File integrity verification configuration
  integrity_verification:
    # Master switch for SHA-256 verification
    enabled: true

    # Expected SHA-256 checksums for file integrity verification
    # These can be overridden by environment variables: ML_MODEL_SHA256, ML_VECTORIZER_SHA256
    expected_checksums:
      model: "af53814d71a48518c2d8c47eab8db9adf2ba40249d6f634b4f059268be750b8e"
      vectorizer: "33052586943574c34884371d9f987e440e7a5d3cb5e85bb8a19fd334f1f610c5"

    # Configuration for SHA-256 calculation
    hash_config:
      chunk_size_bytes: 4096  # Size of chunks when reading files for hashing

# S3 and Download Configuration
s3_utilities:
  # Default environment to use when ENV is not set or invalid
  default_environment: "staging"
