condition_dropdown_table:
  version_number: v0.2
  filename: "CC Taxonomy master"
  input_key:
    - Main condition/term
    - Synonym term 1
    - Synonym term 2
    - Synonym term 3
    - Synonym term 4
    - Legacy term 1
    - Legacy term 2
    - Legacy term 3
    - Legacy term 4
    - Legacy term 5
    - Legacy term 6
    - Legacy term 7
    - Autosuggestion term 1
    - Autosuggestion term 2
    - Autosuggestion term 3
    - Autosuggestion term 4
    - Autosuggestion term 5
    - Autosuggestion term 6
  classification_code: Classification Code
  classification_name: Classification Text
  active_classification: Active classification mapping
  release_notes: |
    Adds synonyms for conditions and includes 5 new terms and mappings. The added terms are
    skin carcinoma, eye cancer, vision cancer, vascular soft tissue sarcoma, and angiosarcoma.
  release_date: 2025-04-14
diagnostic_code_table:
  version_number: v0.6
  filename: "[Release notes] Diagnostic Code to Classification mapping release notes - DC Lookup"
  input_key: DIAGNOSTIC_CODE
  classification_code: CLASSIFICATION_CODE
  classification_name: CLASSIFICATION_TEXT
  release_notes: >
    Added mappings 11 DCs added: 9411 for PTSD, 5012, 5015, and new DCs because of updates to Digestive section of rating schedule.
    3 DCs removed: 5003 for degenerative arthritis, 5017 for gout, and 5010 for post-traumatic arthritis"""
  release_date: 2024-09-12
autosuggestion_table:
  version_number: v0.2
  filename: "CC Taxonomy master"
  active_autocomplete: Active autosuggestion terms
  autocomplete_terms:
    - Autosuggestion term 1
    - Autosuggestion term 2
    - Autosuggestion term 3
    - Autosuggestion term 4
    - Autosuggestion term 5
    - Autosuggestion term 6
  release_notes: >
    No updates to the autosuggestion for this v0.2 release.
  release_date: 2025-04-14
musculoskeletal_lut:
  ankle:
    classification_code: 8991
    classification_name: Musculoskeletal - Ankle
  elbow:
    classification_code: 8993
    classification_name: Musculoskeletal - Elbow
  feet:
    classification_code: 8994
    classification_name: Musculoskeletal - Foot
  foot:
    classification_code: 8994
    classification_name: Musculoskeletal - Foot
  hip:
    classification_code: 8996
    classification_name: Musculoskeletal - Hip
  knee:
    classification_code: 8997
    classification_name: Musculoskeletal - Knee
  low back:
    classification_code: 8998
    classification_name: Musculoskeletal - Mid/Lower Back (Thoracolumbar Spine)
  lower back:
    classification_code: 8998
    classification_name: Musculoskeletal - Mid/Lower Back (Thoracolumbar Spine)
  mid back:
    classification_code: 8998
    classification_name: Musculoskeletal - Mid/Lower Back (Thoracolumbar Spine)
  neck:
    classification_code: 8999
    classification_name: Musculoskeletal - Neck/Upper Back (Cervical Spine)
  shoulder:
    classification_code: 9002
    classification_name: Musculoskeletal - Shoulder
  toe:
    classification_code: 8994
    classification_name: Musculoskeletal - Foot
  toes:
    classification_code: 8994
    classification_name: Musculoskeletal - Foot
  upper back:
    classification_code: 8999
    classification_name: Musculoskeletal - Neck/Upper Back (Cervical Spine)
  wrist:
    classification_code: 9004
    classification_name: Musculoskeletal - Wrist
common_words:
  - left
  - right
  - bilateral
  - in
  - of
  - or
  - the
  - my
  - and
  - chronic
  - to
  - and
  - major
  - than
  - with
  - a
  - va
  - for
  - as
  - has
  - me
  - one
  - use
  - year
  - within
  - worse
  - at
  - have
  - side
  - by
  - frequent
  - mild
  - loud
  - weak
  - bl
  - exam
  - undiagnosed
  - during
  - is
  - when
  - day
  - was
  - all
  - aircraft
  - total
  - moderate
  - noises
  - complete
  - after
  - up
  - it
  - bi
  - daily
  - 'no'
  - had
  - getting
  - also
  - rt
  - sp
  - be
  - see
  - need
  - an
  - which
  - since
  - this
  - jet
  - can't
  - cant
  - pain
  - condition
lut_default_value:
  classification_code: null
  classification_name: null
ai_classification_endpoint:
  url: 'http://localhost:8120/'
  endpoint: 'ml-contention-classification'
ml_classifier:
  model_file: 'src/python_src/util/models/LR_tfidf_fit_model_20250613.pkl'
