condition_dropdown_table:
  version_number: 'v0.5'
  filename: '[Release notes] Contention Text to Classification mapping release notes - Contention Text Lookup'
  input_key: "CONTENTION TEXT"
  classification_code: "CLASSIFICATION CODE"
  classification_name: "CLASSIFICATION TEXT"
  release_notes: 'String with Release Notes'
  release_date: '2024-09-11'
diagnostic_code_table:
  version_number: 'v0.6'
  filename: '[Release notes] Diagnostic Code to Classification mapping release notes - DC Lookup'
  input_key: "DIAGNOSTIC_CODE"
  classification_code: "CLASSIFICATION_CODE"
  classification_name: "CLASSIFICATION_TEXT"
  release_notes: 'String with Release Notes'
  release_date: '2024-09-11'
autosuggestion_table:
  version_number: 'v1.2'
  filename: "[Release notes] Auto-suggestions release notes - Suggested Conditions"
  release_notes: 'String with Release Notes'
  release_date: '2024-09-11'
musculoskeletal_lut:
  ankle:
    classification_code: 8991
    classification_name: Musculoskeletal - Ankle
  elbow:
    classification_code: 8993
    classification_name: Musculoskeletal - Elbow
  feet:
    classification_code: 8994
    classification_name: Musculoskeletal - Foot
  foot:
    classification_code: 8994
    classification_name: Musculoskeletal - Foot
  hip:
    classification_code: 8996
    classification_name: Musculoskeletal - Hip
  knee:
    classification_code: 8997
    classification_name: Musculoskeletal - Knee
  low back:
    classification_code: 8998
    classification_name: Musculoskeletal - Mid/Lower Back (Thoracolumbar Spine)
  lower back:
    classification_code: 8998
    classification_name: Musculoskeletal - Mid/Lower Back (Thoracolumbar Spine)
  mid back:
    classification_code: 8998
    classification_name: Musculoskeletal - Mid/Lower Back (Thoracolumbar Spine)
  neck:
    classification_code: 8999
    classification_name: Musculoskeletal - Neck/Upper Back (Cervical Spine)
  shoulder:
    classification_code: 9002
    classification_name: Musculoskeletal - Shoulder
  toe:
    classification_code: 8994
    classification_name: Musculoskeletal - Foot
  toes:
    classification_code: 8994
    classification_name: Musculoskeletal - Foot
  upper back:
    classification_code: 8999
    classification_name: Musculoskeletal - Neck/Upper Back (Cervical Spine)
  wrist:
    classification_code: 9004
    classification_name: Musculoskeletal - Wrist
common_words:
  - left
  - right
  - bilateral
  - in
  - of
  - or
  - the
  - my
  - and
  - chronic
  - to
  - and
  - major
  - than
  - with
  - a
  - va
  - for
  - as
  - has
  - me
  - one
  - use
  - year
  - within
  - worse
  - at
  - have
  - side
  - by
  - frequent
  - mild
  - loud
  - weak
  - bl
  - exam
  - undiagnosed
  - during
  - is
  - when
  - day
  - was
  - all
  - aircraft
  - total
  - moderate
  - noises
  - complete
  - after
  - up
  - it
  - bi
  - daily
  - 'no'
  - had
  - getting
  - also
  - rt
  - sp
  - be
  - see
  - need
  - an
  - which
  - since
  - this
  - jet
  - can't
  - cant
  - pain
  - condition
expanded_classifier:
  contention_text:
    CONTENTION TEXT
  classification_code:
    CLASSIFICATION CODE
  classification_name:
    CLASSIFICATION TEXT
lut_default_value:
  classification_code: null
  classification_name: null
