name: Release and Update Manifests

on:
  workflow_dispatch:
    inputs:
      environments:
        type: choice
        description: 'Environments to deploy to'
        options:
          - dev
          - dev staging
          - dev staging sandbox
          - dev staging sandbox prod
      commit_sha:
        type: string
        description: 'Commit SHA to deploy (must belong to the selected branch, defaults to latest SHA if not specified)'
        required: false
  workflow_run:
    workflows:
      - 'Build and Push to ECR'
    branches:
      - main
    types:
      - completed

env:
  auto_deploy_envs: 'dev staging'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  validate-sha:
    runs-on: ubuntu-latest
    outputs:
      validated_sha: ${{ steps.validate-sha.outputs.validated_sha }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Validate SHA or use current workflow SHA
        id: validate-sha
        run: |
          COMMIT_SHA="${{ github.event.inputs.commit_sha }}"
          if [[ -n "$COMMIT_SHA" ]]; then
            echo "Validating provided SHA: $COMMIT_SHA"
            git fetch origin ${{ github.ref_name }}
            if git merge-base --is-ancestor $COMMIT_SHA origin/${{ github.ref_name }}; then
              echo "Using SHA $COMMIT_SHA from branch ${{ github.ref_name }}"
              echo "validated_sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
            else
              echo "Error: SHA $COMMIT_SHA does not exist on branch ${{ github.ref_name }}"
              exit 1
            fi
          else
            echo "No SHA provided, using current workflow SHA: ${{ github.sha }}"
            echo "validated_sha=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

  prepare-environments:
    runs-on: ubuntu-latest
    needs: [validate-sha]
    outputs:
      environments: ${{ steps.set-environments.outputs.environments }}
    steps:
      - name: Set to auto deploy environments when not run via workflow dispatch
        if: github.event.inputs.environments == ''
        run: |
          echo "triggered via push to main"
          echo "environments=${{ env.auto_deploy_envs }}" >> $GITHUB_ENV
      - name: Set to environments specified in input when run via workflow dispatch
        if: github.event.inputs.environments != ''
        run: |
          echo "triggered via workflow dispatch"
          echo "environments=${{ github.event.inputs.environments }}" >> $GITHUB_ENV
      - name: Set output
        id: set-environments
        run: |
          echo "environments=${{ env.environments }}" >> $GITHUB_OUTPUT

  can-deploy-to-environment-check:
    runs-on: ubuntu-latest
    needs: [prepare-environments]
    steps:
      - name: Check deployment restrictions
        run: |
          environments="${{ needs.prepare-environments.outputs.environments }}"
          current_branch="${{ github.ref_name }}"

          echo "Current branch: $current_branch"
          echo "Target environments: $environments"

          if [[ ("$environments" == *"sandbox"* || "$environments" == *"prod"*) && "$current_branch" != "main" ]]; then
            echo "Error: Cannot deploy to sandbox or prod environments from branch '$current_branch'"
            echo "Sandbox and prod deployments are only allowed from the main branch"
            exit 1
          fi

          echo "✅ Deployment(s) to '$environments' allowed"

  update-image-tag:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    needs:
      - prepare-environments
      - validate-sha
      - can-deploy-to-environment-check
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GHA_OIDC_ROLE }}
          aws-region: us-gov-west-1

      - name: Get bot token from Parameter Store
        uses: department-of-veterans-affairs/action-inject-ssm-secrets@latest
        with:
          ssm_parameter: /devops/VA_VSP_BOT_GITHUB_TOKEN
          env_variable_name: GITHUB_TOKEN

      - name: Check out vsp-infra-application-manifests
        uses: actions/checkout@v5
        with:
          repository: department-of-veterans-affairs/vsp-infra-application-manifests
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 1
          path: vsp-infra-application-manifests

      - name: Update image tag in infra repo
        run: |
          cd vsp-infra-application-manifests/apps/contention-classification-api
          envs=( ${{ needs.prepare-environments.outputs.environments }} )
          for env in ${envs[*]};
          do
            yq e -i '(.image.tag) |= "${{ needs.validate-sha.outputs.validated_sha }}"' $env/values.yaml
          done
          git diff --unified=0

      - name: Add and Commit file
        uses: EndBug/add-and-commit@v9
        with:
          author_email: 70344339+va-vsp-bot@users.noreply.github.com
          author_name: va-vsp-bot
          cwd: vsp-infra-application-manifests/apps/contention-classification-api
          fetch: false
          message: 'auto-updating contention-classification-api to commit: ${{ needs.validate-sha.outputs.validated_sha }} for env(s): ${{ needs.prepare-environments.outputs.environments }}'
